# config/meta.yml

meta_product_name: "Waterlog"
meta_title: "Waterlog - Find, log and rate waters from all over the world"
meta_description: "We wanted to create a community for water enthusiasts."
meta_image: "waterlog-thumbnail.png" # should exist in `app/assets/images/`